GET /user HTTP/1.1
Host: localhost:26623
Content-Type: application/json

{
  "userList": [
    {
      "name": "vincent1",
      "gender": "man",
      "age": 25
    },
    {
      "name": "vincent2",
      "gender": "man",
      "age": 26
    }
  ]
}